export const CANDIDATES = [
  {
    id: "hilton",
    name: "Steve Hilton",
    title: "Former Fox News host & UK PM adviser",
    party: "Republican",
    lane: "Conservative",
    pollingPct: 22,
    active: true,
  },
  {
    id: "bianco",
    name: "Chad Bianco",
    title: "Riverside County Sheriff",
    party: "Republican",
    lane: "Conservative",
    pollingPct: 18,
    active: true,
  },
  {
    id: "steyer",
    name: "Tom Steyer",
    title: "Billionaire activist & former hedge fund manager",
    party: "Democrat",
    lane: "Progressive",
    pollingPct: 16,
    active: true,
  },
  {
    id: "becerra",
    name: "Xavier Becerra",
    title: "Former U.S. HHS Secretary & CA Attorney General",
    party: "Democrat",
    lane: "Progressive",
    pollingPct: 13,
    active: true,
  },
  {
    id: "porter",
    name: "Katie Porter",
    title: "Former U.S. Representative (CA-47)",
    party: "Democrat",
    lane: "Progressive",
    pollingPct: 11,
    active: true,
  },
  {
    id: "mahan",
    name: "Matt Mahan",
    title: "Mayor, San José",
    party: "Democrat",
    lane: "Moderate",
    pollingPct: 4,
    active: true,
  },
  {
    id: "villaraigosa",
    name: "Antonio Villaraigosa",
    title: "Former Mayor, Los Angeles",
    party: "Democrat",
    lane: "Centrist",
    pollingPct: 3,
    active: true,
  },
  {
    id: "thurmond",
    name: "Tony Thurmond",
    title: "CA Superintendent of Public Instruction",
    party: "Democrat",
    lane: "Progressive",
    pollingPct: 2,
    active: true,
  },
  {
    id: "swalwell",
    name: "Eric Swalwell",
    title: "Former U.S. Representative (CA-14)",
    party: "Democrat",
    lane: "Progressive",
    pollingPct: null,
    active: false,
    suspendedLabel: "Suspended",
  },
  {
    id: "yee",
    name: "Betty Yee",
    title: "Former CA State Controller",
    party: "Democrat",
    lane: "Progressive",
    pollingPct: null,
    active: false,
    suspendedLabel: "Suspended",
  },
];

export const ISSUES = [
  { id: "housing",     label: "Housing",              group: "Core Issues" },
  { id: "homeless",    label: "Homelessness",         group: "Core Issues" },
  { id: "economy",     label: "Economy & taxes",      group: "Core Issues" },
  { id: "energy",      label: "Energy & climate",     group: "Core Issues" },
  { id: "immigration", label: "Immigration & Trump",  group: "Core Issues" },
  { id: "wildfire",    label: "Wildfire & insurance", group: "Additional Issues" },
  { id: "budget",      label: "State budget deficit", group: "Additional Issues" },
  { id: "healthcare",  label: "Healthcare",           group: "Additional Issues" },
  { id: "ai",          label: "AI & tech policy",     group: "Additional Issues" },
  { id: "education",   label: "Education",            group: "Additional Issues" },
  { id: "costliving",  label: "Cost of living",       group: "Additional Issues" },
];

export const CITATIONS = {
  c1:  { source: "CalMatters",      title: "Who are the 2026 California governor candidates?",          url: "https://calmatters.org/california-voter-guide-2026/governor/",                                                                          date: "May 2026" },
  c2:  { source: "KQED",            title: "Voter Guide: California Governor 2026",                      url: "https://www.kqed.org/voterguide/california/governor",                                                                                   date: "May 2026" },
  c3:  { source: "CalMatters",      title: "Governor YIMBY: Most candidates see eye-to-eye on housing",  url: "https://calmatters.org/politics/2026/05/california-governor-housing-2026-yimby/",                                                      date: "May 2026" },
  c4:  { source: "CalMatters",      title: "How will California's next governor handle homelessness?",   url: "https://calmatters.org/politics/2026/05/ca-governor-candidates-homelessness/",                                                          date: "May 2026" },
  c5:  { source: "CalMatters",      title: "Candidates target Steyer, Becerra in free-wheeling debate",  url: "https://calmatters.org/politics/2026/04/governor-race-primary-debate/",                                                                date: "April 2026" },
  c6:  { source: "CBS LA",          title: "Takeaways from the CBS California Governor's Debate",        url: "https://www.cbsnews.com/losangeles/news/top-takeaways-cbs-california-governors-debate/",                                               date: "April 2026" },
  c7:  { source: "PPIC",            title: "Californians and Their Government — Feb 2026 Survey",        url: "https://www.ppic.org/publication/ppic-statewide-survey-californians-and-their-government-february-2026/",                               date: "February 2026" },
  c8:  { source: "EdSource",        title: "California gubernatorial candidates divided over education",  url: "https://edsource.org/2026/california-governors-education-debate/756626",                                                               date: "May 2026" },
  c9:  { source: "NBC News",        title: "Governor candidates tangle over immigration, homelessness",  url: "https://www.nbcnews.com/politics/2026-election/california-governor-candidates-tangle-immigration-homelessness-tense-d-rcna343978",     date: "May 2026" },
  c10: { source: "KPBS",            title: "California governor race explainer",                          url: "https://www.kpbs.org/news/politics/2026/05/04/2026-primary-election-california-governor-race-explainer",                               date: "May 2026" },
  c11: { source: "NewsNation",      title: "Who is Steve Hilton? California governor candidate profile",  url: "https://www.newsnationnow.com/politics/2026-midterm-elections/california-governor-candidate-steve-hilton/",                            date: "May 2026" },
  c12: { source: "CBS News",        title: "California candidates on immigrant health care and ICE",      url: "https://www.cbsnews.com/news/california-immigrant-healthcare-ice-sanctuary-state-2026-governors-race/",                                date: "November 2025" },
  c13: { source: "Hilton campaign", title: "Steve Hilton for Governor — Platform",                        url: "https://stevehiltonforgovernor.com/",                                                                                                   date: "2026" },
  c14: { source: "PBS NewsHour",    title: "Candidates for California governor tangle in testy debate",   url: "https://www.pbs.org/newshour/politics/candidates-for-california-governor-tangle-in-testy-debate-with-mail-voting-already-underway",   date: "May 2026" },
  c15: { source: "SB Independent",  title: "Steve Hilton campaigns in Santa Barbara",                     url: "https://www.independent.com/2026/03/04/republican-steve-hilton-campaigns-for-governor-in-santa-barbara-promotes-califordable-agenda/", date: "March 2026" },
};

export const POSITIONS = {
  hilton: {
    housing:     { text: `Expand housing onto open land outside major cities ("sprawl = the California Dream"); cap housing taxes; strip regulations; cut red tape for faster permitting.`, citations: ["c1", "c11", "c13"] },
    homeless:    { text: `Dismantle "housing first" as a "complete disaster"; redirect all state funding to sober housing; clear encampments first, then triage; $24B in prior spending produced no results.`, citations: ["c4", "c13"] },
    economy:     { text: `No income tax under $100k; 7.5% flat tax above $100k; no new property taxes; cut state budget drastically; eliminate nanny-state agencies and regulations.`, citations: ["c1", "c11", "c13"] },
    energy:      { text: `Suspend environmental regulations to lower gas prices; end "Democrat environment crusade"; skeptical of climate mandates; supports fossil fuels as part of energy mix.`, citations: ["c1", "c13", "c5"] },
    immigration: { text: `Trump-endorsed; full 100% cooperation with ICE; repeal CA sanctuary law (SB 54); enforce all federal immigration law at state and local level.`, citations: ["c1", "c12", "c13"] },
    wildfire:    { text: `Blames wildfire crisis on environmental policies blocking forest management; wants to cut bureaucracy preventing wildfire rebuilding.`, citations: ["c6", "c13"] },
    budget:      { text: `Cut state spending dramatically; eliminate wasteful agencies; opposes all tax increases; points to Florida (similar population, lower spend, better outcomes) as model.`, citations: ["c13", "c14"] },
    healthcare:  { text: `Believes everyone should have access to healthcare but wants limited, market-based coverage; opposes single-payer state system.`, citations: ["c12"] },
    ai:          { text: `Pro-tech; supports removing regulatory barriers for all businesses including tech; no specific AI fee or worker displacement policy.`, citations: ["c11", "c13"] },
    education:   { text: `Problem is accountability, not funding; grade and reward/fire teachers by performance; opposes progressive curriculum mandates.`, citations: ["c11", "c13"] },
    costliving:  { text: `Tax cuts, deregulation, and spending reductions as the primary levers; suspend gas tax; lower energy costs by ending environmental mandates.`, citations: ["c13", "c14"] },
  },
  bianco: {
    housing:     { text: `Cut red tape to build housing faster; reduce regulatory burden; boost oil and gas production to grow the economy and household income.`, citations: ["c1", "c2", "c10"] },
    homeless:    { text: `Demand accountability for $24B+ spent with no results; clear encampments; end cycle of spending without outcomes.`, citations: ["c2", "c5", "c14"] },
    economy:     { text: `Eliminate state income tax entirely (currently >60% of state revenue); eliminate gas tax; oppose all new taxes; cut regulations; make California oil independent; support tech sector for jobs.`, citations: ["c1", "c2", "c10"] },
    energy:      { text: `Boost oil and gas production; suspend environmental regulations; wildfire root cause is failed environmental policy, not climate change; opposes climate mandates.`, citations: ["c1", "c6", "c10"] },
    immigration: { text: `Endorsed Trump ("time to put a felon in the White House"); overturn sanctuary law; full cooperation with ICE; is suing state over sanctuary status.`, citations: ["c1", "c2", "c12"] },
    wildfire:    { text: `Root causes are government environmental policies blocking forest management; cut bureaucracy blocking fire recovery and rebuilding.`, citations: ["c6", "c14"] },
    budget:      { text: `Eliminate income tax (the largest revenue source) as top priority despite $35B+ projected deficit; cut spending programs to compensate.`, citations: ["c2", "c14"] },
    healthcare:  { text: `Less specific; accountability and common sense approach; opposes state-run single-payer system.`, citations: ["c2", "c14"] },
    ai:          { text: `Supports tech sector as job creator; no specific AI policy; pro-deregulation stance extends to tech industry.`, citations: ["c2"] },
    education:   { text: `Cut wasteful spending; hold schools accountable; Democrats' progressive agenda is "destroying California"; supports parent rights.`, citations: ["c2", "c8"] },
    costliving:  { text: `Eliminate income and gas taxes as the primary cost relief; cut regulations; boost domestic energy production to lower prices.`, citations: ["c2", "c13", "c14"] },
  },
  steyer: {
    housing:     { text: `YIMBY-endorsed; pledges 1M homes in 4 years; build on surplus public land; invest in prefab housing; protect renters; raise commercial property taxes to fund housing.`, citations: ["c1", "c2", "c3"] },
    homeless:    { text: `Supports mandated mental health treatment after repeated shelter refusals; addresses homelessness through broad affordability and housing production.`, citations: ["c4", "c5"] },
    economy:     { text: `Corporations pay their fair share; close water's-edge corporate tax loophole; raise commercial property taxes (Prop 13 reform); only candidate backing billionaire wealth tax; opposes gas tax suspension.`, citations: ["c1", "c2", "c5"] },
    energy:      { text: `Strong climate hawk; taxes on oil industry profits; challenge utility monopolies; long-term electrification; hold fossil fuel companies accountable for wildfire damage.`, citations: ["c1", "c6", "c14"] },
    immigration: { text: `Avowed Trump critic; spent millions on 2017 impeachment push; proposes ICE watchdog investigative unit; links rising gas prices to war in Iran.`, citations: ["c2", "c5"] },
    wildfire:    { text: `Hold fossil fuel companies accountable for homes lost in Palisades and Eaton fires; climate-first approach to wildfire risk reduction.`, citations: ["c6", "c14"] },
    budget:      { text: `New revenue via commercial property tax reform, corporate loophole closing, oil profit taxes, and AI fee; opposes cuts as primary solution.`, citations: ["c2", "c7"] },
    healthcare:  { text: `Supports state-level single-payer healthcare; free preschool for age 3+; lower electric bills 25%; has not specified how to backfill lost federal funds.`, citations: ["c2", "c10"] },
    ai:          { text: `Collect fee on AI usage to support displaced workers; challenge investor-owned utility monopolies; only candidate with a specific AI economic policy.`, citations: ["c1", "c10"] },
    education:   { text: `Free preschool for age 3+; free community college; invest in displaced worker retraining; increase school funding broadly.`, citations: ["c1", "c2", "c8"] },
    costliving:  { text: `Cut electric bills 25%; free preschool and community college; 1M affordable homes; corporations pay their share to lower consumer costs.`, citations: ["c2", "c10", "c14"] },
  },
  becerra: {
    housing:     { text: `Denser urban and transit-oriented development; higher labor standards on streamlined projects; use state funds to keep people housed before they become homeless.`, citations: ["c1", "c2", "c3"] },
    homeless:    { text: `Declare state emergency to freeze utility and insurance rates; use state money to keep people housed before they hit the streets; fight price gouging.`, citations: ["c2", "c4"] },
    economy:     { text: `Fight price gouging and unjustified rate hikes; use state power where market fails; higher taxes on mega-wealthy and passive income; protect Medi-Cal; opposes gas tax suspension.`, citations: ["c1", "c2", "c5"] },
    energy:      { text: `Open to revising climate goals to keep fuel affordable for middle class; emergency utility rate freezes; backed climate legal battles as CA Attorney General.`, citations: ["c1", "c2"] },
    immigration: { text: `Top priority is resisting Trump; sued Trump administration 120+ times as AG; strongly defends sanctuary law; calls Mahan's critiques "Trump lies."`, citations: ["c1", "c2", "c9"] },
    wildfire:    { text: `Declare emergency to freeze insurance rates; insurers must be transparent on pricing; invest in prevention now to avoid paying for failure later.`, citations: ["c6", "c14"] },
    budget:      { text: `Higher taxes on mega-wealthy and passive income; use state power to generate revenue; protect existing programs; fight federal fund losses.`, citations: ["c2", "c7"] },
    healthcare:  { text: `Fought for and defended ACA as AG; protect Medi-Cal; fight insurance denials; committed to healthcare access without a specific single-payer plan.`, citations: ["c1", "c2"] },
    ai:          { text: `Less specific; general innovation and affordability focus; no specific AI tax or worker displacement policy.`, citations: ["c1"] },
    education:   { text: `Named housing, healthcare, and education as top priorities; protect public school funding; less specific on K–12 structural reform.`, citations: ["c1", "c8"] },
    costliving:  { text: `Fight price gouging; freeze utility and insurance rates via emergency declaration; keep people housed to avoid downstream homelessness costs.`, citations: ["c2", "c7", "c14"] },
  },
  porter: {
    housing:     { text: `Denser housing near transit; skeptical of mandating high labor standards on every streamlined project; fund housing via corporate tax increases.`, citations: ["c1", "c2", "c3"] },
    homeless:    { text: `Fortify healthcare system; expand care access; supports forced shelter offers before mandated treatment.`, citations: ["c2", "c4"] },
    economy:     { text: `Cut state income taxes for families under $100k; raise corporate taxes on large businesses; fund 2 free years of UC/CSU tuition; opposes gas tax suspension.`, citations: ["c1", "c2", "c5"] },
    energy:      { text: `Keep refineries open while pursuing electrification; no immediate gas-tax suspension; protect environmental standards.`, citations: ["c2", "c5"] },
    immigration: { text: `Points to congressional record grilling Trump officials; promises to fortify CA; refuses corporate and lobbyist donations.`, citations: ["c2", "c9"] },
    wildfire:    { text: `Sign laws preventing insurers from denying wildfire claims; consumer-protection track record applied to insurance industry.`, citations: ["c2", "c6"] },
    budget:      { text: `Raise corporate taxes to fund middle-class tax cuts and free tuition; has not specified how to backfill federal healthcare funding losses.`, citations: ["c2", "c7"] },
    healthcare:  { text: `Supports state-level single-payer healthcare; prevent insurance denials; lower drug costs; backed by consumer advocacy career.`, citations: ["c2", "c10"] },
    ai:          { text: `Consumer-protection lens on corporate AI power; no specific AI fee; opposes corporate concentration generally.`, citations: ["c2"] },
    education:   { text: `2 free years of UC/CSU tuition for families under $100k funded by corporate tax hike; protect public schools from federal cuts.`, citations: ["c2", "c8"] },
    costliving:  { text: `Cut middle-income state taxes; lower drug and grocery costs; personal narrative as single working mother grounds her affordability message.`, citations: ["c2", "c7", "c14"] },
  },
  mahan: {
    housing:     { text: `Deregulate housing; cap local development fees; relax building codes; cut taxes on housing development; backed by Silicon Valley donors.`, citations: ["c1", "c2", "c3"] },
    homeless:    { text: `Tiny homes expansion; arrest those refusing repeated shelter offers; involuntary commitment 30–60 days then transitional housing; reduced San José street homelessness ~25% since 2019.`, citations: ["c1", "c4", "c9"] },
    economy:     { text: `Opposes new taxes; suspend gas tax temporarily; tie government officials' pay to performance outcomes.`, citations: ["c1", "c2", "c5"] },
    energy:      { text: `Suspend gas tax; keep refineries open while pursuing electrification; skeptical of aggressive climate mandates that raise prices.`, citations: ["c2", "c5"] },
    immigration: { text: `Anti-MAGA; tougher enforcement posture; attacked Becerra for "failing" on immigration at HHS; supports law enforcement cooperation.`, citations: ["c5", "c9"] },
    wildfire:    { text: `Keep refineries open; skeptical of aggressive climate regulations; less specific on insurance market reform.`, citations: ["c5", "c6"] },
    budget:      { text: `Opposes new taxes; cut wasteful spending; tie government pay to performance; pro-efficiency over new revenue.`, citations: ["c1", "c2"] },
    healthcare:  { text: `Less specific; moderate approach; general affordability focus without structural overhaul or single-payer commitment.`, citations: ["c2"] },
    ai:          { text: `Pro-tech industry; backed by Silicon Valley donors; opposes new business taxes that would burden tech sector.`, citations: ["c1"] },
    education:   { text: `Tie government pay to performance; supports accountability measures; less specific on K–12 spending structure.`, citations: ["c8"] },
    costliving:  { text: `Suspend gas tax; cut housing fees; oppose new taxes; tech-sector growth as economic engine for affordability.`, citations: ["c2", "c7"] },
  },
  villaraigosa: {
    housing:     { text: `Boost homebuyer assistance programs; defend Prop 13 (open to modest changes); streamline permitting; built more homeless housing in L.A. than prior 12 years combined.`, citations: ["c1", "c2", "c3"] },
    homeless:    { text: `Tiny homes; withhold funds from counties not implementing CARE Court; expand mental health workforce via college training; reform involuntary commitment standards.`, citations: ["c4", "c9"] },
    economy:     { text: `Moderate; opposes gas tax suspension; supports oil and gas as transition fuel; moratorium on some climate regulations to protect affordability.`, citations: ["c1", "c2", "c5"] },
    energy:      { text: `Views oil and gas as transitional energy; moratorium on certain climate mandates; all-of-above strategy; acknowledges climate change is real.`, citations: ["c1", "c2", "c6"] },
    immigration: { text: `Create task force to ensure ICE agents follow state law; attacked Becerra for immigration failures at HHS; enforce existing sanctuary law, not repeal it.`, citations: ["c2", "c9"] },
    wildfire:    { text: `Expand Cal Fire; increase prescribed burns; fix insurance crisis so fire victims can rebuild; all-of-above strategy.`, citations: ["c6", "c14"] },
    budget:      { text: `Moderate approach; defend Prop 13; skeptical of broad new taxes; targeted spending reforms; moratorium on costly climate regulations.`, citations: ["c2", "c7"] },
    healthcare:  { text: `Less specific; protect healthcare access; moderate; no single-payer commitment.`, citations: ["c2"] },
    ai:          { text: `Less specific; no stated AI policy position.`, citations: ["c1"] },
    education:   { text: `Significant public investment track record as L.A. mayor and Assembly speaker; less detailed on specific K–12 reforms.`, citations: ["c8"] },
    costliving:  { text: `Defend Prop 13 to protect homeowner costs; moratorium on climate regulations that raise prices; keep refineries open.`, citations: ["c2", "c7"] },
  },
  thurmond: {
    housing:     { text: `2 million new units of housing; down-payment assistance grants for buyers; build more student housing via UC/CSU bonds.`, citations: ["c2", "c8"] },
    homeless:    { text: `Focus on building housing as the core solution; more public support for affordable housing rather than enforcement-first.`, citations: ["c4", "c8"] },
    economy:     { text: `Supports proposed one-time billionaire wealth tax — only candidate formally backing it; increase school and public program funding.`, citations: ["c1", "c8"] },
    energy:      { text: `Supports clean energy investment; backs climate protections; less specific than other progressives on energy transition policy.`, citations: ["c8"] },
    immigration: { text: `Passed law keeping ICE out of CA schools as Superintendent; supports abolishing ICE; strong immigrant rights stance.`, citations: ["c1", "c8"] },
    wildfire:    { text: `Less specific; general support for climate-resilient infrastructure investment.`, citations: ["c8"] },
    budget:      { text: `Billionaire wealth tax as revenue source; increase funding for public programs; opposes austerity cuts.`, citations: ["c1", "c7", "c8"] },
    healthcare:  { text: `Healthcare for all; backfill Medi-Cal from federal cuts; expand mental health funding broadly.`, citations: ["c8"] },
    ai:          { text: `Less specific; no stated AI policy position.`, citations: ["c8"] },
    education:   { text: `Head of CA's $150B public school system; increase K–12 per-pupil funding; universal preschool for 4-year-olds; universal school meals; dyslexia screening; fully fund public schools.`, citations: ["c1", "c8"] },
    costliving:  { text: `Fund public programs via billionaire tax; address food and grocery costs; free school meals; universal preschool.`, citations: ["c7", "c8"] },
  },
};
